"""Notification domain.

The engine's vocabulary: what we may send (category), where it goes (channel),
what happened (delivery state), the Persian copy (message catalogue), the
audit record (Notification), admin fan-out (Broadcast), and the timing rules
(schedule, quiet hours).

Deliberately free of transport concerns. Nothing here knows what aiogram is,
which is why the same aggregate serves both the Telegram push and the Mini App
inbox.
"""

from geekvpn.domain.notifications.broadcast import (
    DEFAULT_BATCH_SIZE,
    MAX_BODY,
    MIN_BODY,
    MIN_TITLE,
    Broadcast,
)
from geekvpn.domain.notifications.enums import (
    AudienceKind,
    BroadcastState,
    DeliveryState,
    JobKind,
    NotificationCategory,
    NotificationChannel,
    SuppressionReason,
)
from geekvpn.domain.notifications.errors import (
    BroadcastNotEditable,
    BroadcastNotFound,
    EmptyAudience,
    IllegalBroadcastTransition,
    MissingTemplateField,
    NotificationError,
    NotificationNotFound,
    TemplateNotFound,
)
from geekvpn.domain.notifications.events import (
    BroadcastCancelled,
    BroadcastCompleted,
    BroadcastScheduled,
    BroadcastStarted,
    NotificationDeferred,
    NotificationFailed,
    NotificationQueued,
    NotificationRead,
    NotificationSent,
    NotificationSuppressed,
    ReminderJobCompleted,
)
from geekvpn.domain.notifications.message import (
    CATALOG,
    PREVIEW_LIMIT,
    MessageTemplate,
    RenderedMessage,
    fa_digits,
    fa_gib,
    fa_number,
    fa_toman,
    render,
    template_keys,
)
from geekvpn.domain.notifications.notification import (
    MAX_ATTEMPTS,
    DeliveryAttempt,
    Notification,
)
from geekvpn.domain.notifications.preferences import (
    DEFAULT_PREFERENCES,
    IRAN_UTC_OFFSET_HOURS,
    QUIET_END,
    QUIET_START,
    ChannelPreferences,
    NotificationPreferences,
    QuietHours,
    local_hour,
)
from geekvpn.domain.notifications.schedule import (
    DEFAULT_INTERVALS,
    EXPIRY_REMINDER_DAYS,
    TRAFFIC_EXHAUSTED_PERCENT,
    TRAFFIC_THRESHOLDS,
    ScheduleEntry,
    broadcast_dedupe_key,
    campaign_dedupe_key,
    default_schedule,
    due_entries,
    expiry_dedupe_key,
    expiry_threshold_for,
    traffic_dedupe_key,
    traffic_threshold_for,
)

__all__ = [
    "CATALOG",
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_INTERVALS",
    "DEFAULT_PREFERENCES",
    "EXPIRY_REMINDER_DAYS",
    "IRAN_UTC_OFFSET_HOURS",
    "MAX_ATTEMPTS",
    "MAX_BODY",
    "MIN_BODY",
    "MIN_TITLE",
    "PREVIEW_LIMIT",
    "QUIET_END",
    "QUIET_START",
    "TRAFFIC_EXHAUSTED_PERCENT",
    "TRAFFIC_THRESHOLDS",
    "AudienceKind",
    "Broadcast",
    "BroadcastCancelled",
    "BroadcastCompleted",
    "BroadcastNotEditable",
    "BroadcastNotFound",
    "BroadcastScheduled",
    "BroadcastStarted",
    "BroadcastState",
    "ChannelPreferences",
    "DeliveryAttempt",
    "DeliveryState",
    "EmptyAudience",
    "IllegalBroadcastTransition",
    "JobKind",
    "MessageTemplate",
    "MissingTemplateField",
    "Notification",
    "NotificationCategory",
    "NotificationChannel",
    "NotificationDeferred",
    "NotificationError",
    "NotificationFailed",
    "NotificationNotFound",
    "NotificationPreferences",
    "NotificationQueued",
    "NotificationRead",
    "NotificationSent",
    "NotificationSuppressed",
    "QuietHours",
    "ReminderJobCompleted",
    "RenderedMessage",
    "ScheduleEntry",
    "SuppressionReason",
    "TemplateNotFound",
    "broadcast_dedupe_key",
    "campaign_dedupe_key",
    "default_schedule",
    "due_entries",
    "expiry_dedupe_key",
    "expiry_threshold_for",
    "fa_digits",
    "fa_gib",
    "fa_number",
    "fa_toman",
    "local_hour",
    "render",
    "template_keys",
    "traffic_dedupe_key",
    "traffic_threshold_for",
]
