"""Catalog, promotions and pricing.

Revision ID: 0002_catalog_and_pricing
Revises: 0001_identity_and_audit
Create Date: Phase 4

The check constraints here are not decoration. Three of them encode product
decisions that must survive a hand-written UPDATE at 2am:

* `catalog_products_published_requires_panel` - nothing can be sold that
  provisioning cannot deliver.
* `catalog_plans_type_invariants` - the three plan types are three genuinely
  different products, and a hybrid row is unsellable or a lie.
* `catalog_campaigns_flash_sale_needs_end` - a flash sale with no end is a
  permanent price cut nobody remembers to switch off.

The migration is written by hand rather than autogenerated so the constraint
names match the naming convention exactly and the downgrade is real.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0002_catalog_and_pricing"
down_revision = "0001_identity_and_audit"
branch_labels = None
depends_on = None


_TIMESTAMPS = (
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        server_default=sa.text("now()"),
        nullable=False,
    ),
    sa.Column(
        "updated_at",
        sa.DateTime(timezone=True),
        server_default=sa.text("now()"),
        nullable=False,
    ),
)


def upgrade() -> None:
    # -- categories --------------------------------------------------------
    op.create_table(
        "catalog_categories",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name_fa", sa.String(length=128), nullable=False),
        sa.Column("name_en", sa.String(length=128), nullable=True),
        sa.Column("description_fa", sa.String(length=512), nullable=True),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("state", sa.String(length=16), nullable=False, server_default="draft"),
        *_TIMESTAMPS,
        sa.CheckConstraint(
            "state IN ('draft', 'published', 'archived')",
            name="ck_catalog_categories_catalog_categories_state",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_catalog_categories"),
        sa.UniqueConstraint("slug", name="uq_catalog_categories_slug"),
    )
    op.create_index(
        "ix_catalog_categories_created_at", "catalog_categories", ["created_at"]
    )
    op.create_index("ix_catalog_categories_state", "catalog_categories", ["state"])

    # -- products ----------------------------------------------------------
    op.create_table(
        "catalog_products",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("category_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column("name_fa", sa.String(length=128), nullable=False),
        sa.Column("tagline_fa", sa.String(length=256), nullable=True),
        sa.Column("description_fa", sa.String(length=2048), nullable=True),
        sa.Column(
            "features_fa",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("badge_fa", sa.String(length=64), nullable=True),
        sa.Column("accent_color", sa.String(length=32), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "is_featured", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column("state", sa.String(length=16), nullable=False, server_default="draft"),
        sa.Column("panel_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "node_tags",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        *_TIMESTAMPS,
        sa.CheckConstraint(
            "tier IN ('direct', 'tunnel', 'elite')",
            name="ck_catalog_products_catalog_products_tier",
        ),
        sa.CheckConstraint(
            "state IN ('draft', 'published', 'archived')",
            name="ck_catalog_products_catalog_products_state",
        ),
        sa.CheckConstraint(
            "state <> 'published' OR panel_id IS NOT NULL",
            name="ck_catalog_products_catalog_products_published_requires_panel",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["catalog_categories.id"],
            name="fk_catalog_products_category_id_catalog_categories",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_catalog_products"),
        sa.UniqueConstraint("slug", name="uq_catalog_products_slug"),
    )
    op.create_index("ix_catalog_products_created_at", "catalog_products", ["created_at"])
    op.create_index(
        "ix_catalog_products_category_id", "catalog_products", ["category_id"]
    )
    op.create_index("ix_catalog_products_tier", "catalog_products", ["tier"])
    op.create_index("ix_catalog_products_state", "catalog_products", ["state"])
    op.create_index("ix_catalog_products_panel_id", "catalog_products", ["panel_id"])
    op.create_index(
        "ix_catalog_products_category_state",
        "catalog_products",
        ["category_id", "state"],
    )

    # -- plans -------------------------------------------------------------
    op.create_table(
        "catalog_plans",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("product_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("plan_type", sa.String(length=16), nullable=False),
        sa.Column("name_fa", sa.String(length=128), nullable=False),
        sa.Column("description_fa", sa.String(length=1024), nullable=True),
        sa.Column("badge_fa", sa.String(length=64), nullable=True),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("quota_gib", sa.Integer(), nullable=True),
        sa.Column("daily_quota_gib", sa.Integer(), nullable=True),
        sa.Column("device_limit", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("base_price", sa.BigInteger(), nullable=False),
        sa.Column("compare_at_price", sa.BigInteger(), nullable=True),
        sa.Column("min_price", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("cashback_bps", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("max_per_user", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "is_featured", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column("state", sa.String(length=16), nullable=False, server_default="draft"),
        *_TIMESTAMPS,
        sa.CheckConstraint(
            "plan_type IN ('traffic', 'unlimited', 'duration')",
            name="ck_catalog_plans_catalog_plans_type",
        ),
        sa.CheckConstraint(
            "state IN ('draft', 'published', 'archived')",
            name="ck_catalog_plans_catalog_plans_state",
        ),
        sa.CheckConstraint(
            "base_price >= 0", name="ck_catalog_plans_catalog_plans_price_non_negative"
        ),
        sa.CheckConstraint(
            "min_price >= 0", name="ck_catalog_plans_catalog_plans_floor_non_negative"
        ),
        sa.CheckConstraint(
            "min_price <= base_price",
            name="ck_catalog_plans_catalog_plans_floor_below_price",
        ),
        sa.CheckConstraint(
            "compare_at_price IS NULL OR compare_at_price > base_price",
            name="ck_catalog_plans_catalog_plans_compare_at_above_price",
        ),
        sa.CheckConstraint(
            "duration_days > 0 AND duration_days <= 3650",
            name="ck_catalog_plans_catalog_plans_duration_range",
        ),
        sa.CheckConstraint(
            "cashback_bps >= 0 AND cashback_bps <= 3000",
            name="ck_catalog_plans_catalog_plans_cashback_range",
        ),
        sa.CheckConstraint(
            "device_limit > 0", name="ck_catalog_plans_catalog_plans_device_limit"
        ),
        sa.CheckConstraint(
            "(plan_type = 'traffic' AND quota_gib IS NOT NULL AND quota_gib > 0"
            " AND daily_quota_gib IS NULL)"
            " OR (plan_type = 'unlimited' AND quota_gib IS NULL"
            " AND daily_quota_gib IS NULL)"
            " OR (plan_type = 'duration' AND daily_quota_gib IS NOT NULL"
            " AND daily_quota_gib > 0 AND quota_gib IS NULL)",
            name="ck_catalog_plans_catalog_plans_type_invariants",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["catalog_products.id"],
            name="fk_catalog_plans_product_id_catalog_products",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_catalog_plans"),
        sa.UniqueConstraint("slug", name="uq_catalog_plans_slug"),
    )
    op.create_index("ix_catalog_plans_created_at", "catalog_plans", ["created_at"])
    op.create_index("ix_catalog_plans_product_id", "catalog_plans", ["product_id"])
    op.create_index("ix_catalog_plans_plan_type", "catalog_plans", ["plan_type"])
    op.create_index("ix_catalog_plans_state", "catalog_plans", ["state"])
    op.create_index(
        "ix_catalog_plans_product_state", "catalog_plans", ["product_id", "state"]
    )

    # -- coupons -----------------------------------------------------------
    op.create_table(
        "catalog_coupons",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("description_fa", sa.String(length=512), nullable=True),
        sa.Column("discount_kind", sa.String(length=16), nullable=False),
        sa.Column("discount_value", sa.BigInteger(), nullable=False),
        sa.Column("max_discount", sa.BigInteger(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "scope",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("max_redemptions", sa.Integer(), nullable=True),
        sa.Column("max_per_user", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("redemption_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "min_order_amount", sa.BigInteger(), nullable=False, server_default="0"
        ),
        sa.Column("target_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "stacks_with_campaign",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "first_purchase_only",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "state", sa.String(length=16), nullable=False, server_default="published"
        ),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        *_TIMESTAMPS,
        sa.CheckConstraint(
            "kind IN ('public', 'single_use', 'per_user', 'targeted')",
            name="ck_catalog_coupons_catalog_coupons_kind",
        ),
        sa.CheckConstraint(
            "discount_kind IN ('percentage', 'fixed_amount')",
            name="ck_catalog_coupons_catalog_coupons_discount_kind",
        ),
        sa.CheckConstraint(
            "state IN ('draft', 'published', 'archived')",
            name="ck_catalog_coupons_catalog_coupons_state",
        ),
        sa.CheckConstraint(
            "discount_value > 0",
            name="ck_catalog_coupons_catalog_coupons_discount_positive",
        ),
        sa.CheckConstraint(
            "discount_kind <> 'percentage' OR discount_value <= 10000",
            name="ck_catalog_coupons_catalog_coupons_percentage_range",
        ),
        sa.CheckConstraint(
            "redemption_count >= 0",
            name="ck_catalog_coupons_catalog_coupons_count_non_negative",
        ),
        sa.CheckConstraint(
            "starts_at IS NULL OR ends_at IS NULL OR ends_at > starts_at",
            name="ck_catalog_coupons_catalog_coupons_window_ordered",
        ),
        sa.CheckConstraint(
            "kind <> 'single_use' OR max_redemptions = 1",
            name="ck_catalog_coupons_catalog_coupons_single_use_cap",
        ),
        sa.CheckConstraint(
            "kind <> 'targeted' OR target_user_id IS NOT NULL",
            name="ck_catalog_coupons_catalog_coupons_targeted_requires_user",
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
            name="fk_catalog_coupons_target_user_id_users",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["admins.id"],
            name="fk_catalog_coupons_created_by_admins",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_catalog_coupons"),
        sa.UniqueConstraint("code", name="uq_catalog_coupons_code"),
    )
    op.create_index("ix_catalog_coupons_created_at", "catalog_coupons", ["created_at"])
    op.create_index("ix_catalog_coupons_ends_at", "catalog_coupons", ["ends_at"])
    op.create_index("ix_catalog_coupons_state", "catalog_coupons", ["state"])
    op.create_index(
        "ix_catalog_coupons_target_user_id", "catalog_coupons", ["target_user_id"]
    )

    # -- coupon redemptions ------------------------------------------------
    op.create_table(
        "catalog_coupon_redemptions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("coupon_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("order_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("discount", sa.BigInteger(), nullable=False),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["coupon_id"],
            ["catalog_coupons.id"],
            name="fk_catalog_coupon_redemptions_coupon_id_catalog_coupons",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_catalog_coupon_redemptions_user_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_catalog_coupon_redemptions"),
        sa.UniqueConstraint(
            "coupon_id",
            "user_id",
            "order_id",
            name="catalog_coupon_redemptions_unique",
        ),
    )
    op.create_index(
        "ix_catalog_coupon_redemptions_coupon_id",
        "catalog_coupon_redemptions",
        ["coupon_id"],
    )
    op.create_index(
        "ix_catalog_coupon_redemptions_user_id",
        "catalog_coupon_redemptions",
        ["user_id"],
    )
    op.create_index(
        "ix_catalog_coupon_redemptions_order_id",
        "catalog_coupon_redemptions",
        ["order_id"],
    )
    op.create_index(
        "ix_catalog_coupon_redemptions_redeemed_at",
        "catalog_coupon_redemptions",
        ["redeemed_at"],
    )
    op.create_index(
        "ix_catalog_coupon_redemptions_coupon_user",
        "catalog_coupon_redemptions",
        ["coupon_id", "user_id"],
    )

    # -- campaigns ---------------------------------------------------------
    op.create_table(
        "catalog_campaigns",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name_fa", sa.String(length=128), nullable=False),
        sa.Column("description_fa", sa.String(length=1024), nullable=True),
        sa.Column("banner_url", sa.String(length=512), nullable=True),
        sa.Column("discount_kind", sa.String(length=16), nullable=False),
        sa.Column("discount_value", sa.BigInteger(), nullable=False),
        sa.Column("max_discount", sa.BigInteger(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "scope",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("max_redemptions", sa.Integer(), nullable=True),
        sa.Column("redemption_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("priority", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("state", sa.String(length=16), nullable=False, server_default="draft"),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        *_TIMESTAMPS,
        sa.CheckConstraint(
            "kind IN ('seasonal', 'flash_sale', 'launch', 'winback')",
            name="ck_catalog_campaigns_catalog_campaigns_kind",
        ),
        sa.CheckConstraint(
            "discount_kind IN ('percentage', 'fixed_amount')",
            name="ck_catalog_campaigns_catalog_campaigns_discount_kind",
        ),
        sa.CheckConstraint(
            "state IN ('draft', 'published', 'archived')",
            name="ck_catalog_campaigns_catalog_campaigns_state",
        ),
        sa.CheckConstraint(
            "discount_value > 0",
            name="ck_catalog_campaigns_catalog_campaigns_discount_positive",
        ),
        sa.CheckConstraint(
            "discount_kind <> 'percentage' OR discount_value <= 10000",
            name="ck_catalog_campaigns_catalog_campaigns_percentage_range",
        ),
        sa.CheckConstraint(
            "starts_at IS NULL OR ends_at IS NULL OR ends_at > starts_at",
            name="ck_catalog_campaigns_catalog_campaigns_window_ordered",
        ),
        sa.CheckConstraint(
            "kind <> 'flash_sale' OR ends_at IS NOT NULL",
            name="ck_catalog_campaigns_catalog_campaigns_flash_sale_needs_end",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["admins.id"],
            name="fk_catalog_campaigns_created_by_admins",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_catalog_campaigns"),
        sa.UniqueConstraint("slug", name="uq_catalog_campaigns_slug"),
    )
    op.create_index(
        "ix_catalog_campaigns_created_at", "catalog_campaigns", ["created_at"]
    )
    op.create_index("ix_catalog_campaigns_kind", "catalog_campaigns", ["kind"])
    op.create_index("ix_catalog_campaigns_ends_at", "catalog_campaigns", ["ends_at"])
    op.create_index("ix_catalog_campaigns_priority", "catalog_campaigns", ["priority"])
    op.create_index("ix_catalog_campaigns_state", "catalog_campaigns", ["state"])
    op.create_index(
        "ix_catalog_campaigns_state_priority",
        "catalog_campaigns",
        ["state", "priority", "ends_at"],
    )

    # -- pricing runtime settings -----------------------------------------
    # Seeded rather than left absent so the admin panel renders every knob on a
    # fresh install instead of an empty page. `ON CONFLICT DO NOTHING` keeps
    # this safe to re-run and stops it clobbering values on an existing system.
    op.execute(
        """
        INSERT INTO platform_settings (key, value, description, is_secret)
        VALUES
          ('pricing.rounding_step', '1000'::jsonb,
           'Prices are rounded down to this many Toman.', false),
          ('pricing.allow_coupon_campaign_stacking', 'true'::jsonb,
           'Whether a coupon may be combined with a running campaign.', false),
          ('pricing.max_total_discount_bps', '7000'::jsonb,
           'Hard ceiling on campaign plus coupon combined, in basis points.', false),
          ('pricing.cashback.enabled', 'true'::jsonb,
           'Whether purchases earn wallet credit.', false),
          ('pricing.cashback.base_bps', '0'::jsonb,
           'Platform-wide cashback floor added to each plan rate.', false),
          ('pricing.cashback.max_bps', '2000'::jsonb,
           'Ceiling on plan plus platform plus loyalty cashback.', false),
          ('pricing.cashback.max_amount', 'null'::jsonb,
           'Absolute cashback cap per order in Toman. Null means no cap.', false),
          ('pricing.referral.enabled', 'true'::jsonb,
           'Whether the referral programme is active.', false),
          ('pricing.referral.signup_bonus', '0'::jsonb,
           'Credit for the referrer at signup. Zero discourages fake accounts.', false),
          ('pricing.referral.first_purchase_bps', '1000'::jsonb,
           'Referrer share of the invitee first order, in basis points.', false),
          ('pricing.referral.recurring_bps', '0'::jsonb,
           'Referrer share of subsequent orders, in basis points.', false),
          ('pricing.referral.invitee_bonus', '0'::jsonb,
           'Welcome credit for the invited customer, in Toman.', false),
          ('pricing.referral.max_reward_per_order', 'null'::jsonb,
           'Cap on a single referral reward in Toman. Null means no cap.', false)
        ON CONFLICT (key) DO NOTHING
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DELETE FROM platform_settings
        WHERE key LIKE 'pricing.%' OR key LIKE 'cashback.%' OR key LIKE 'referral.%'
        """
    )
    # Dropped children-first: plans reference products, products reference
    # categories, redemptions reference coupons.
    op.drop_table("catalog_campaigns")
    op.drop_table("catalog_coupon_redemptions")
    op.drop_table("catalog_coupons")
    op.drop_table("catalog_plans")
    op.drop_table("catalog_products")
    op.drop_table("catalog_categories")
