"""Billing, support, notifications and provisioning.

Revision ID: 0003_billing_and_support
Revises: 0002_catalog_and_pricing
Create Date: Phase 12

Eighteen tables in one revision, because they ship together and a half-applied
subset is not a state the application can run in.

Four constraints here are business rules that must survive a hand-written
UPDATE at 2am, which is exactly when someone will try one:

* ``billing_payments_refund_within_capture`` - you cannot refund more money
  than you actually took. Without it, one wrong number turns a refund into a
  withdrawal from the company.
* ``billing_wallet_balance_non_negative`` - a wallet cannot go below zero.
  Overdraft is not a product we sell.
* ``uq_wallet_user_kind_reference`` - the same top-up reference cannot be
  credited twice. This is the last line of defence behind the receipt digest,
  and it is a database constraint rather than application logic because two
  operators clicking approve at the same instant beat any Python check.
* ``uq_notify_user_dedupe`` - one user gets one notification per dedupe key,
  so a restarted reminder job cannot re-send yesterday's warnings.

Ordering matters: ``nodes`` precedes ``subscriptions`` and ``orders`` precedes
``subscriptions`` because of foreign keys, and the downgrade reverses that.

Written by hand rather than autogenerated so the constraint names match the
naming convention exactly and the downgrade is real.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0003_billing_and_support"
down_revision = "0002_catalog_and_pricing"
branch_labels = None
depends_on = None


def _timestamps() -> tuple[sa.Column, sa.Column]:
    """Fresh Column objects per table.

    A module-level tuple of Columns cannot be reused: SQLAlchemy binds a Column
    to the first table it is attached to, and the second table would silently
    lose the columns.
    """
    return (
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )


INVOICE_STATES = "'open', 'paid', 'void', 'refunded'"
PAYMENT_METHODS = "'wallet', 'card', 'crypto', 'gateway', 'credit'"
PAYMENT_STATES = (
    "'draft', 'awaiting_proof', 'pending_review', 'pending_gateway', 'approved', "
    "'rejected', 'refunded', 'partially_refunded', 'expired', 'failed'"
)
TRANSACTION_KINDS = (
    "'topup', 'purchase', 'refund', 'cashback', 'referral_reward', 'adjustment', 'overpayment'"
)
REFUND_REASONS = "'customer_request', 'service_failure', 'duplicate_payment', 'fraud', 'goodwill'"
REFUND_DESTINATIONS = "'wallet', 'original'"
TICKET_CATEGORIES = "'connection', 'payment', 'account', 'speed', 'technical', 'other'"
TICKET_PRIORITIES = "'low', 'normal', 'high', 'urgent'"
TICKET_STATES = "'open', 'waiting_user', 'answered', 'closed'"
MESSAGE_KINDS = "'customer', 'support', 'note', 'status_change'"
NOTIFICATION_CATEGORIES = "'expiry', 'traffic', 'promos', 'news', 'critical'"
DELIVERY_STATES = "'pending', 'sent', 'failed', 'suppressed', 'deferred'"
BROADCAST_STATES = "'draft', 'scheduled', 'sending', 'sent', 'cancelled', 'failed'"
AUDIENCE_KINDS = (
    "'all', 'active_subscribers', 'expired', 'expiring_soon', 'never_purchased', 'tier', 'explicit'"
)
JOB_KINDS = (
    "'expiration_reminder', 'traffic_reminder', 'broadcast_dispatch', "
    "'campaign_announce', 'deferred_flush'"
)
ORDER_STATES = "'pending', 'paid', 'provisioning', 'active', 'failed', 'cancelled', 'refunded'"
SUBSCRIPTION_STATES = "'active', 'expired', 'exhausted', 'suspended', 'revoked'"
NODE_STATES = "'online', 'degraded', 'offline', 'maintenance', 'retired'"


def _upgrade_billing() -> None:
    op.create_table(
        "billing_invoices",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False, server_default="open"),
        sa.Column("lines", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("subtotal", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("discount_total", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("total", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("plan_id", sa.String(length=64), nullable=True),
        sa.Column("plan_name", sa.String(length=128), nullable=True),
        sa.Column("campaign_id", sa.String(length=64), nullable=True),
        sa.Column("coupon_code", sa.String(length=64), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_by_payment_id", sa.String(length=64), nullable=True),
        sa.Column("notes_fa", sa.String(length=512), nullable=True),
        sa.Column("subject_fa", sa.String(length=256), nullable=False, server_default=""),
        sa.Column("meta", postgresql.JSONB(), nullable=False, server_default="{}"),
        *_timestamps(),
        sa.CheckConstraint(
            f"state IN ({INVOICE_STATES})",
            name="ck_billing_invoices_billing_invoices_state",
        ),
        sa.CheckConstraint(
            "total >= 0", name="ck_billing_invoices_billing_invoices_total_positive"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_billing_invoices"),
        sa.UniqueConstraint("number", name="uq_billing_invoices_number"),
    )
    op.create_index("ix_billing_invoices_user_id", "billing_invoices", ["user_id"])
    op.create_index("ix_billing_invoices_state", "billing_invoices", ["state"])
    op.create_index("ix_billing_invoices_plan_id", "billing_invoices", ["plan_id"])
    op.create_index("ix_billing_invoices_campaign_id", "billing_invoices", ["campaign_id"])
    op.create_index("ix_billing_invoices_coupon_code", "billing_invoices", ["coupon_code"])
    op.create_index("ix_billing_invoices_issued_at", "billing_invoices", ["issued_at"])
    op.create_index("ix_billing_invoices_paid_at", "billing_invoices", ["paid_at"])
    op.create_index("ix_billing_invoices_created_at", "billing_invoices", ["created_at"])
    op.create_index("ix_billing_invoices_user_state", "billing_invoices", ["user_id", "state"])
    op.create_index("ix_billing_invoices_paid_at_state", "billing_invoices", ["paid_at", "state"])

    op.create_table(
        "billing_payments",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("invoice_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False, server_default="draft"),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("captured", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("refunded_total", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("gateway_key", sa.String(length=32), nullable=True),
        sa.Column("gateway_reference", sa.String(length=128), nullable=True),
        sa.Column("proof", postgresql.JSONB(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.BigInteger(), nullable=True),
        sa.Column("reason_fa", sa.String(length=512), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.String(length=200), nullable=True),
        sa.Column("meta", postgresql.JSONB(), nullable=False, server_default="{}"),
        *_timestamps(),
        sa.CheckConstraint(
            f"method IN ({PAYMENT_METHODS})",
            name="ck_billing_payments_billing_payments_method",
        ),
        sa.CheckConstraint(
            f"state IN ({PAYMENT_STATES})",
            name="ck_billing_payments_billing_payments_state",
        ),
        sa.CheckConstraint(
            "amount > 0", name="ck_billing_payments_billing_payments_amount_positive"
        ),
        sa.CheckConstraint(
            "refunded_total >= 0 AND refunded_total <= captured",
            name="ck_billing_payments_billing_payments_refund_within_capture",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["billing_invoices.id"],
            name="fk_billing_payments_invoice_id_billing_invoices",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_billing_payments"),
    )
    op.create_index("ix_billing_payments_invoice_id", "billing_payments", ["invoice_id"])
    op.create_index("ix_billing_payments_user_id", "billing_payments", ["user_id"])
    op.create_index("ix_billing_payments_method", "billing_payments", ["method"])
    op.create_index("ix_billing_payments_state", "billing_payments", ["state"])
    op.create_index("ix_billing_payments_expires_at", "billing_payments", ["expires_at"])
    op.create_index("ix_billing_payments_settled_at", "billing_payments", ["settled_at"])
    op.create_index("ix_billing_payments_reviewed_by", "billing_payments", ["reviewed_by"])
    op.create_index("ix_billing_payments_created_at", "billing_payments", ["created_at"])
    op.create_index(
        "ix_billing_payments_state_created", "billing_payments", ["state", "created_at"]
    )
    op.create_index("ix_billing_payments_user_state", "billing_payments", ["user_id", "state"])

    op.create_table(
        "billing_refunds",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("payment_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.String(length=24), nullable=False),
        sa.Column("destination", sa.String(length=16), nullable=False),
        sa.Column("note_fa", sa.String(length=512), nullable=False, server_default=""),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        *_timestamps(),
        sa.CheckConstraint(
            f"reason IN ({REFUND_REASONS})",
            name="ck_billing_refunds_billing_refunds_reason",
        ),
        sa.CheckConstraint(
            f"destination IN ({REFUND_DESTINATIONS})",
            name="ck_billing_refunds_billing_refunds_destination",
        ),
        sa.CheckConstraint("amount > 0", name="ck_billing_refunds_billing_refunds_amount_positive"),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["billing_payments.id"],
            name="fk_billing_refunds_payment_id_billing_payments",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_billing_refunds"),
    )
    op.create_index("ix_billing_refunds_payment_id", "billing_refunds", ["payment_id"])
    op.create_index("ix_billing_refunds_user_id", "billing_refunds", ["user_id"])
    op.create_index("ix_billing_refunds_refunded_at", "billing_refunds", ["refunded_at"])
    op.create_index("ix_billing_refunds_created_at", "billing_refunds", ["created_at"])

    op.create_table(
        "billing_wallet_entries",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("balance_after", sa.BigInteger(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description_fa", sa.String(length=256), nullable=False, server_default=""),
        sa.Column("reference", sa.String(length=128), nullable=True),
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        *_timestamps(),
        sa.CheckConstraint(
            f"kind IN ({TRANSACTION_KINDS})",
            name="ck_billing_wallet_entries_billing_wallet_kind",
        ),
        sa.CheckConstraint(
            "balance_after >= 0",
            name="ck_billing_wallet_entries_billing_wallet_balance_non_negative",
        ),
        sa.CheckConstraint(
            "amount <> 0",
            name="ck_billing_wallet_entries_billing_wallet_amount_non_zero",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_billing_wallet_entries"),
        sa.UniqueConstraint("user_id", "kind", "reference", name="uq_wallet_user_kind_reference"),
    )
    op.create_index("ix_billing_wallet_entries_user_id", "billing_wallet_entries", ["user_id"])
    op.create_index("ix_billing_wallet_entries_kind", "billing_wallet_entries", ["kind"])
    op.create_index(
        "ix_billing_wallet_entries_occurred_at", "billing_wallet_entries", ["occurred_at"]
    )
    op.create_index(
        "ix_billing_wallet_entries_created_at", "billing_wallet_entries", ["created_at"]
    )
    op.create_index(
        "ix_billing_wallet_user_occurred",
        "billing_wallet_entries",
        ["user_id", "occurred_at"],
    )

    op.create_table(
        "billing_receipt_digests",
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("payment_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("reference", sa.String(length=128), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("digest", name="pk_billing_receipt_digests"),
    )
    op.create_index(
        "ix_billing_receipt_digests_payment_id", "billing_receipt_digests", ["payment_id"]
    )
    op.create_index("ix_billing_receipt_digests_user_id", "billing_receipt_digests", ["user_id"])
    op.create_index(
        "ix_billing_receipt_digests_reference", "billing_receipt_digests", ["reference"]
    )
    op.create_index(
        "ix_billing_receipt_digests_created_at", "billing_receipt_digests", ["created_at"]
    )

    op.create_table(
        "billing_card_accounts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("holder_fa", sa.String(length=128), nullable=False),
        sa.Column("bank_fa", sa.String(length=64), nullable=False),
        sa.Column("card_number", sa.String(length=19), nullable=False),
        sa.Column("sheba", sa.String(length=26), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("daily_limit", sa.BigInteger(), nullable=True),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_billing_card_accounts"),
        sa.UniqueConstraint("card_number", name="uq_billing_card_accounts_card_number"),
    )
    op.create_index("ix_billing_card_accounts_active", "billing_card_accounts", ["active"])
    op.create_index("ix_billing_card_accounts_created_at", "billing_card_accounts", ["created_at"])


def _upgrade_support() -> None:
    op.create_table(
        "support_tickets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("reference", sa.String(length=24), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("subject_fa", sa.String(length=256), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.String(length=8), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False, server_default="open"),
        sa.Column("assignee_id", sa.BigInteger(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("waiting_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_reply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=False, server_default="0"),
        *_timestamps(),
        sa.CheckConstraint(
            f"category IN ({TICKET_CATEGORIES})",
            name="ck_support_tickets_support_tickets_category",
        ),
        sa.CheckConstraint(
            f"priority IN ({TICKET_PRIORITIES})",
            name="ck_support_tickets_support_tickets_priority",
        ),
        sa.CheckConstraint(
            f"state IN ({TICKET_STATES})",
            name="ck_support_tickets_support_tickets_state",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_support_tickets"),
        sa.UniqueConstraint("reference", name="uq_support_tickets_reference"),
    )
    op.create_index("ix_support_tickets_user_id", "support_tickets", ["user_id"])
    op.create_index("ix_support_tickets_category", "support_tickets", ["category"])
    op.create_index("ix_support_tickets_priority", "support_tickets", ["priority"])
    op.create_index("ix_support_tickets_state", "support_tickets", ["state"])
    op.create_index("ix_support_tickets_assignee_id", "support_tickets", ["assignee_id"])
    op.create_index("ix_support_tickets_opened_at", "support_tickets", ["opened_at"])
    op.create_index("ix_support_tickets_waiting_since", "support_tickets", ["waiting_since"])
    op.create_index("ix_support_tickets_created_at", "support_tickets", ["created_at"])
    op.create_index(
        "ix_support_tickets_state_waiting", "support_tickets", ["state", "waiting_since"]
    )
    op.create_index("ix_support_tickets_user_state", "support_tickets", ["user_id", "state"])

    op.create_table(
        "support_messages",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("ticket_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("body_fa", sa.Text(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("template_id", sa.String(length=64), nullable=True),
        sa.Column("attachments", postgresql.JSONB(), nullable=False, server_default="[]"),
        *_timestamps(),
        sa.CheckConstraint(
            f"kind IN ({MESSAGE_KINDS})",
            name="ck_support_messages_support_messages_kind",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["support_tickets.id"],
            name="fk_support_messages_ticket_id_support_tickets",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_support_messages"),
    )
    op.create_index("ix_support_messages_ticket_id", "support_messages", ["ticket_id"])
    op.create_index("ix_support_messages_kind", "support_messages", ["kind"])
    op.create_index("ix_support_messages_author_id", "support_messages", ["author_id"])
    op.create_index("ix_support_messages_sent_at", "support_messages", ["sent_at"])
    op.create_index("ix_support_messages_template_id", "support_messages", ["template_id"])
    op.create_index("ix_support_messages_created_at", "support_messages", ["created_at"])
    op.create_index("ix_support_messages_ticket_sent", "support_messages", ["ticket_id", "sent_at"])

    op.create_table(
        "support_templates",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("title_fa", sa.String(length=128), nullable=False),
        sa.Column("body_fa", sa.Text(), nullable=False),
        sa.Column("categories", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("use_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_support_templates"),
    )
    op.create_index("ix_support_templates_active", "support_templates", ["active"])
    op.create_index("ix_support_templates_created_at", "support_templates", ["created_at"])


def _upgrade_notifications() -> None:
    op.create_table(
        "notify_notifications",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("template_key", sa.String(length=64), nullable=False),
        sa.Column("title_fa", sa.String(length=256), nullable=False),
        sa.Column("body_fa", sa.Text(), nullable=False),
        sa.Column("action", sa.String(length=256), nullable=True),
        sa.Column("deliveries", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("state", sa.String(length=16), nullable=False, server_default="pending"),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("send_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("broadcast_id", sa.String(length=64), nullable=True),
        sa.Column("dedupe_key", sa.String(length=160), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=True),
        *_timestamps(),
        sa.CheckConstraint(
            f"category IN ({NOTIFICATION_CATEGORIES})",
            name="ck_notify_notifications_notify_notifications_category",
        ),
        sa.CheckConstraint(
            f"state IN ({DELIVERY_STATES})",
            name="ck_notify_notifications_notify_notifications_state",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_notify_notifications"),
        sa.UniqueConstraint("user_id", "dedupe_key", name="uq_notify_user_dedupe"),
    )
    op.create_index("ix_notify_notifications_user_id", "notify_notifications", ["user_id"])
    op.create_index("ix_notify_notifications_category", "notify_notifications", ["category"])
    op.create_index(
        "ix_notify_notifications_template_key", "notify_notifications", ["template_key"]
    )
    op.create_index("ix_notify_notifications_state", "notify_notifications", ["state"])
    op.create_index("ix_notify_notifications_queued_at", "notify_notifications", ["queued_at"])
    op.create_index("ix_notify_notifications_send_after", "notify_notifications", ["send_after"])
    op.create_index(
        "ix_notify_notifications_broadcast_id", "notify_notifications", ["broadcast_id"]
    )
    op.create_index("ix_notify_notifications_source", "notify_notifications", ["source"])
    op.create_index("ix_notify_notifications_created_at", "notify_notifications", ["created_at"])
    op.create_index("ix_notify_user_queued", "notify_notifications", ["user_id", "queued_at"])
    op.create_index("ix_notify_state_send_after", "notify_notifications", ["state", "send_after"])

    op.create_table(
        "notify_preferences",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("expiry", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("traffic", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("promos", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("news", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("telegram", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("miniapp", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("quiet_enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("quiet_start_hour", sa.Integer(), nullable=False, server_default="23"),
        sa.Column("quiet_end_hour", sa.Integer(), nullable=False, server_default="8"),
        *_timestamps(),
        sa.CheckConstraint(
            "quiet_start_hour BETWEEN 0 AND 23 AND quiet_end_hour BETWEEN 0 AND 23",
            name="ck_notify_preferences_notify_preferences_quiet_hours_range",
        ),
        sa.PrimaryKeyConstraint("user_id", name="pk_notify_preferences"),
    )
    op.create_index("ix_notify_preferences_created_at", "notify_preferences", ["created_at"])

    op.create_table(
        "notify_broadcasts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("title_fa", sa.String(length=256), nullable=False),
        sa.Column("body_fa", sa.Text(), nullable=False),
        sa.Column("action", sa.String(length=256), nullable=True),
        sa.Column("category", sa.String(length=16), nullable=False, server_default="news"),
        sa.Column("state", sa.String(length=16), nullable=False, server_default="draft"),
        sa.Column("audience_kind", sa.String(length=24), nullable=False),
        sa.Column("audience_filter", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recipient_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("sent_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("failed_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("suppressed_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("cancelled_by", sa.BigInteger(), nullable=True),
        sa.Column("error", sa.String(length=512), nullable=True),
        *_timestamps(),
        sa.CheckConstraint(
            f"state IN ({BROADCAST_STATES})",
            name="ck_notify_broadcasts_notify_broadcasts_state",
        ),
        sa.CheckConstraint(
            f"audience_kind IN ({AUDIENCE_KINDS})",
            name="ck_notify_broadcasts_notify_broadcasts_audience",
        ),
        sa.CheckConstraint(
            f"category IN ({NOTIFICATION_CATEGORIES})",
            name="ck_notify_broadcasts_notify_broadcasts_category",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_notify_broadcasts"),
    )
    op.create_index("ix_notify_broadcasts_state", "notify_broadcasts", ["state"])
    op.create_index("ix_notify_broadcasts_scheduled_for", "notify_broadcasts", ["scheduled_for"])
    op.create_index("ix_notify_broadcasts_created_at", "notify_broadcasts", ["created_at"])
    op.create_index(
        "ix_notify_broadcasts_state_scheduled",
        "notify_broadcasts",
        ["state", "scheduled_for"],
    )

    op.create_table(
        "notify_jobs",
        sa.Column("job", sa.String(length=32), nullable=False),
        sa.Column("interval_minutes", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_duration_ms", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.String(length=512), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
        sa.CheckConstraint(f"job IN ({JOB_KINDS})", name="ck_notify_jobs_notify_jobs_kind"),
        sa.CheckConstraint(
            "interval_minutes > 0", name="ck_notify_jobs_notify_jobs_interval_positive"
        ),
        sa.PrimaryKeyConstraint("job", name="pk_notify_jobs"),
    )
    op.create_index("ix_notify_jobs_created_at", "notify_jobs", ["created_at"])


def _upgrade_provisioning() -> None:
    # nodes first: subscriptions point at it.
    op.create_table(
        "nodes",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name_fa", sa.String(length=128), nullable=False),
        sa.Column("panel_kind", sa.String(length=24), nullable=False),
        sa.Column("base_url", sa.String(length=256), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False, server_default="online"),
        sa.Column("capacity", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("account_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("traffic_used_mib", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("accepting_new", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("last_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=512), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        *_timestamps(),
        sa.CheckConstraint(f"state IN ({NODE_STATES})", name="ck_nodes_nodes_state"),
        sa.CheckConstraint(
            "capacity >= 0 AND account_count >= 0",
            name="ck_nodes_nodes_counts_non_negative",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_nodes"),
    )
    op.create_index("ix_nodes_panel_kind", "nodes", ["panel_kind"])
    op.create_index("ix_nodes_country_code", "nodes", ["country_code"])
    op.create_index("ix_nodes_state", "nodes", ["state"])
    op.create_index("ix_nodes_accepting_new", "nodes", ["accepting_new"])
    op.create_index("ix_nodes_created_at", "nodes", ["created_at"])

    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False, server_default="pending"),
        sa.Column("plan_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("product_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("plan_name_fa", sa.String(length=128), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("traffic_mib", sa.BigInteger(), nullable=True),
        sa.Column("device_limit", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("list_price", sa.BigInteger(), nullable=False),
        sa.Column("discount", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("total", sa.BigInteger(), nullable=False),
        sa.Column("campaign_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("coupon_code", sa.String(length=64), nullable=True),
        sa.Column("invoice_id", sa.String(length=64), nullable=True),
        sa.Column("is_renewal", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("renews_subscription_id", sa.String(length=64), nullable=True),
        sa.Column("placed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provisioned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.String(length=512), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False, server_default="bot"),
        *_timestamps(),
        sa.CheckConstraint(f"state IN ({ORDER_STATES})", name="ck_orders_orders_state"),
        sa.CheckConstraint(
            "total >= 0 AND discount >= 0", name="ck_orders_orders_amounts_non_negative"
        ),
        sa.CheckConstraint("duration_days > 0", name="ck_orders_orders_duration_positive"),
        sa.PrimaryKeyConstraint("id", name="pk_orders"),
        sa.UniqueConstraint("number", name="uq_orders_number"),
    )
    op.create_index("ix_orders_user_id", "orders", ["user_id"])
    op.create_index("ix_orders_state", "orders", ["state"])
    op.create_index("ix_orders_plan_id", "orders", ["plan_id"])
    op.create_index("ix_orders_product_id", "orders", ["product_id"])
    op.create_index("ix_orders_campaign_id", "orders", ["campaign_id"])
    op.create_index("ix_orders_coupon_code", "orders", ["coupon_code"])
    op.create_index("ix_orders_invoice_id", "orders", ["invoice_id"])
    op.create_index("ix_orders_is_renewal", "orders", ["is_renewal"])
    op.create_index("ix_orders_renews_subscription_id", "orders", ["renews_subscription_id"])
    op.create_index("ix_orders_placed_at", "orders", ["placed_at"])
    op.create_index("ix_orders_paid_at", "orders", ["paid_at"])
    op.create_index("ix_orders_source", "orders", ["source"])
    op.create_index("ix_orders_created_at", "orders", ["created_at"])
    op.create_index("ix_orders_paid_at_state", "orders", ["paid_at", "state"])
    op.create_index("ix_orders_user_placed", "orders", ["user_id", "placed_at"])

    op.create_table(
        "subscriptions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("plan_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False, server_default="active"),
        sa.Column("node_id", sa.String(length=64), nullable=True),
        sa.Column("remote_id", sa.String(length=128), nullable=True),
        sa.Column("remote_username", sa.String(length=128), nullable=True),
        sa.Column("subscription_url", sa.String(length=512), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("traffic_limit_mib", sa.BigInteger(), nullable=True),
        sa.Column("traffic_used_mib", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("device_limit", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notified_expiry_days", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column(
            "notified_traffic_percents",
            postgresql.JSONB(),
            nullable=False,
            server_default="[]",
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoke_reason_fa", sa.String(length=512), nullable=True),
        *_timestamps(),
        sa.CheckConstraint(
            f"state IN ({SUBSCRIPTION_STATES})",
            name="ck_subscriptions_subscriptions_state",
        ),
        sa.CheckConstraint(
            "traffic_used_mib >= 0", name="ck_subscriptions_subscriptions_used_non_negative"
        ),
        sa.CheckConstraint(
            "expires_at > started_at", name="ck_subscriptions_subscriptions_dates_ordered"
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name="fk_subscriptions_order_id_orders",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
            name="fk_subscriptions_node_id_nodes",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_subscriptions"),
    )
    op.create_index("ix_subscriptions_user_id", "subscriptions", ["user_id"])
    op.create_index("ix_subscriptions_order_id", "subscriptions", ["order_id"])
    op.create_index("ix_subscriptions_plan_id", "subscriptions", ["plan_id"])
    op.create_index("ix_subscriptions_state", "subscriptions", ["state"])
    op.create_index("ix_subscriptions_node_id", "subscriptions", ["node_id"])
    op.create_index("ix_subscriptions_remote_id", "subscriptions", ["remote_id"])
    op.create_index("ix_subscriptions_expires_at", "subscriptions", ["expires_at"])
    op.create_index("ix_subscriptions_created_at", "subscriptions", ["created_at"])
    op.create_index("ix_subscriptions_state_expires", "subscriptions", ["state", "expires_at"])
    op.create_index("ix_subscriptions_user_state", "subscriptions", ["user_id", "state"])

    op.create_table(
        "referrals",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("referrer_id", sa.BigInteger(), nullable=False),
        sa.Column("invitee_id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("converted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_order_id", sa.String(length=64), nullable=True),
        sa.Column("reward_paid", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("invitee_bonus_paid", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("revenue_generated", sa.BigInteger(), nullable=False, server_default="0"),
        *_timestamps(),
        sa.CheckConstraint(
            "referrer_id <> invitee_id", name="ck_referrals_referrals_no_self_referral"
        ),
        sa.CheckConstraint("reward_paid >= 0", name="ck_referrals_referrals_reward_non_negative"),
        sa.PrimaryKeyConstraint("id", name="pk_referrals"),
        sa.UniqueConstraint("invitee_id", name="uq_referrals_invitee"),
    )
    op.create_index("ix_referrals_referrer_id", "referrals", ["referrer_id"])
    op.create_index("ix_referrals_code", "referrals", ["code"])
    op.create_index("ix_referrals_joined_at", "referrals", ["joined_at"])
    op.create_index("ix_referrals_converted_at", "referrals", ["converted_at"])
    op.create_index("ix_referrals_created_at", "referrals", ["created_at"])
    op.create_index("ix_referrals_referrer_converted", "referrals", ["referrer_id", "converted_at"])

    op.create_table(
        "funnel_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("stage", sa.String(length=24), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False, server_default="bot"),
        sa.Column("context", postgresql.JSONB(), nullable=False, server_default="{}"),
        # No timestamp columns: FunnelEventModel does not use TimestampMixin.
        # A funnel event already carries occurred_at, and a second, subtly
        # different "when" column is how analytics queries start disagreeing
        # with each other.
        sa.PrimaryKeyConstraint("id", name="pk_funnel_events"),
    )
    op.create_index("ix_funnel_events_user_id", "funnel_events", ["user_id"])
    op.create_index("ix_funnel_events_stage", "funnel_events", ["stage"])
    op.create_index("ix_funnel_events_occurred_at", "funnel_events", ["occurred_at"])
    op.create_index("ix_funnel_stage_occurred", "funnel_events", ["stage", "occurred_at"])
    op.create_index("ix_funnel_user_stage", "funnel_events", ["user_id", "stage"])


def upgrade() -> None:
    _upgrade_billing()
    _upgrade_support()
    _upgrade_notifications()
    _upgrade_provisioning()


def downgrade() -> None:
    # Reverse dependency order. Indexes go with their tables.
    for table in (
        "funnel_events",
        "referrals",
        "subscriptions",
        "orders",
        "nodes",
        "notify_jobs",
        "notify_broadcasts",
        "notify_preferences",
        "notify_notifications",
        "support_templates",
        "support_messages",
        "support_tickets",
        "billing_card_accounts",
        "billing_receipt_digests",
        "billing_wallet_entries",
        "billing_refunds",
        "billing_payments",
        "billing_invoices",
    ):
        op.drop_table(table)
