"""Analytics domain: how the business is doing, in Persian.

Everything here is a pure calculation over already-collected numbers. No
repository, no clock, no I/O -- which is what lets the same code answer the
admin panel, a CSV export and a scheduled Telegram digest without three
definitions of "revenue".
"""

from geekvpn.domain.analytics.calendar import (
    MONTH_NAMES_FA,
    WEEKDAY_NAMES_FA,
    fa_digits,
    jalali_date_fa,
    jalali_day_label,
    jalali_month_label,
    jalali_weekday,
    to_jalali,
)
from geekvpn.domain.analytics.dashboard import (
    ActionItem,
    AnalyticsBundle,
    OperatorDashboard,
)
from geekvpn.domain.analytics.enums import (
    BadgeKind,
    FunnelStage,
    Granularity,
    MetricFormat,
    MetricKey,
    SegmentKind,
    TrendDirection,
)
from geekvpn.domain.analytics.errors import (
    AnalyticsError,
    InvalidDateRange,
    SeriesMismatch,
    UnknownMetric,
)
from geekvpn.domain.analytics.funnel import (
    LEAK_THRESHOLD_PERCENT,
    Funnel,
    FunnelStep,
)
from geekvpn.domain.analytics.gamification import (
    LEVEL_LABELS_FA,
    LEVEL_THRESHOLDS,
    Badge,
    PlayerProfile,
    earned_badges,
    level_for,
    level_label_fa,
    points_for,
    points_to_next_level,
)
from geekvpn.domain.analytics.metrics import (
    FLAT_THRESHOLD_PERCENT,
    MetricCard,
    fa_number,
    format_value,
    percent_change,
    ratio_percent,
    safe_divide,
)
from geekvpn.domain.analytics.nodes import (
    CRITICAL_LOAD_PERCENT,
    WARN_LOAD_PERCENT,
    FleetUsage,
    NodeUsage,
)
from geekvpn.domain.analytics.referral import (
    CampaignPerformance,
    ReferralPerformance,
    ReferrerStanding,
    campaign_breakdown,
    leaderboard,
)
from geekvpn.domain.analytics.retention import (
    AT_RISK_DAYS,
    CHURN_GRACE_DAYS,
    Cohort,
    CohortCell,
    CohortTable,
    RetentionSummary,
    is_at_risk,
    is_churned,
)
from geekvpn.domain.analytics.revenue import (
    MIB_PER_GIB,
    PlanSales,
    RevenueTotals,
    TrafficSold,
    gib_from_mib,
    revenue_by_plan,
    traffic_by_plan,
)
from geekvpn.domain.analytics.segmentation import (
    DORMANT_DAYS,
    LOYAL_MIN_ORDERS,
    NEW_CUSTOMER_DAYS,
    WHALE_MIN_SPEND,
    CustomerSnapshot,
    SegmentReport,
    SegmentStat,
    classify,
    matches,
)
from geekvpn.domain.analytics.series import (
    DEFAULT_TOP_N,
    OTHER_LABEL_FA,
    Breakdown,
    BreakdownSlice,
    TimePoint,
    TimeSeries,
)
from geekvpn.domain.analytics.timeframe import (
    MAX_RANGE_DAYS,
    PRESET_DAYS,
    DateRange,
    bucket_label_fa,
    utc_now,
)

__all__ = [
    "AT_RISK_DAYS",
    "CHURN_GRACE_DAYS",
    "CRITICAL_LOAD_PERCENT",
    "DEFAULT_TOP_N",
    "DORMANT_DAYS",
    "FLAT_THRESHOLD_PERCENT",
    "LEAK_THRESHOLD_PERCENT",
    "LEVEL_LABELS_FA",
    "LEVEL_THRESHOLDS",
    "LOYAL_MIN_ORDERS",
    "MAX_RANGE_DAYS",
    "MIB_PER_GIB",
    "MONTH_NAMES_FA",
    "NEW_CUSTOMER_DAYS",
    "OTHER_LABEL_FA",
    "PRESET_DAYS",
    "WARN_LOAD_PERCENT",
    "WEEKDAY_NAMES_FA",
    "WHALE_MIN_SPEND",
    "ActionItem",
    "AnalyticsBundle",
    "AnalyticsError",
    "Badge",
    "BadgeKind",
    "Breakdown",
    "BreakdownSlice",
    "CampaignPerformance",
    "Cohort",
    "CohortCell",
    "CohortTable",
    "CustomerSnapshot",
    "DateRange",
    "FleetUsage",
    "Funnel",
    "FunnelStage",
    "FunnelStep",
    "Granularity",
    "InvalidDateRange",
    "MetricCard",
    "MetricFormat",
    "MetricKey",
    "NodeUsage",
    "OperatorDashboard",
    "PlanSales",
    "PlayerProfile",
    "ReferralPerformance",
    "ReferrerStanding",
    "RetentionSummary",
    "RevenueTotals",
    "SegmentKind",
    "SegmentReport",
    "SegmentStat",
    "SeriesMismatch",
    "TimePoint",
    "TimeSeries",
    "TrafficSold",
    "TrendDirection",
    "UnknownMetric",
    "bucket_label_fa",
    "campaign_breakdown",
    "classify",
    "earned_badges",
    "fa_digits",
    "fa_number",
    "format_value",
    "gib_from_mib",
    "is_at_risk",
    "is_churned",
    "jalali_date_fa",
    "jalali_day_label",
    "jalali_month_label",
    "jalali_weekday",
    "leaderboard",
    "level_for",
    "level_label_fa",
    "matches",
    "percent_change",
    "points_for",
    "points_to_next_level",
    "ratio_percent",
    "revenue_by_plan",
    "safe_divide",
    "to_jalali",
    "traffic_by_plan",
    "utc_now",
]
