'use client'

import * as React from 'react'
import { Copy } from 'lucide-react'

import { ApiError, api } from '@/lib/api'
import type { CreatedReseller } from '@/lib/types'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogBody,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Field, Input } from '@/components/ui/input'

const USERNAME_PATTERN = /^[a-z0-9][a-z0-9_.-]{2,}$/

/**
 * Creating a reseller.
 *
 * A login and a reseller record are created together, in one request. Either
 * alone is a broken state: an account with the role and no record signs in and
 * can do nothing, and a record with no account is a price list nobody can
 * reach.
 *
 * The second screen is the whole reason this is a dialog rather than a row you
 * type into. The password is generated by the server, returned exactly once,
 * and stored only as a hash - so this is the one moment it exists anywhere
 * readable, and the dialog refuses to look like a form you can dismiss without
 * noticing.
 */
export function NewResellerDialog({
  onClose,
  onCreated,
}: {
  onClose: () => void
  onCreated: () => void
}) {
  const [username, setUsername] = React.useState('')
  const [nameFa, setNameFa] = React.useState('')
  const [discount, setDiscount] = React.useState('20')
  const [contact, setContact] = React.useState('')
  const [busy, setBusy] = React.useState(false)
  const [error, setError] = React.useState<string | null>(null)
  const [created, setCreated] = React.useState<CreatedReseller | null>(null)
  const [copied, setCopied] = React.useState(false)

  const percent = Number(discount)
  const valid =
    USERNAME_PATTERN.test(username) &&
    nameFa.trim().length > 0 &&
    Number.isInteger(percent) &&
    percent >= 0 &&
    percent <= 90

  const submit = async () => {
    setBusy(true)
    setError(null)
    try {
      setCreated(
        await api.createReseller({
          username,
          nameFa: nameFa.trim(),
          discountPercent: percent,
          contactFa: contact.trim() || null,
        }),
      )
      onCreated()
    } catch (thrown) {
      setError(thrown instanceof ApiError ? thrown.messageFa : 'ساخت نماینده انجام نشد.')
    } finally {
      setBusy(false)
    }
  }

  const copy = async () => {
    if (!created) return
    try {
      await navigator.clipboard.writeText(
        `نام کاربری: ${created.username}\nرمز عبور: ${created.password}`,
      )
      setCopied(true)
    } catch {
      // A browser that refuses clipboard access is not a failure worth an
      // error banner: the value is on screen and can be selected by hand.
      setCopied(false)
    }
  }

  if (created) {
    return (
      <Dialog open onOpenChange={onClose}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>نماینده ساخته شد</DialogTitle>
            <DialogDescription>
              این رمز فقط همین یک بار نمایش داده می‌شود. اگر آن را نبندید بدون کپی
              کردن، راهی برای دیدن دوباره‌اش نیست و باید حساب را بازنشانی کنید.
            </DialogDescription>
          </DialogHeader>
          <DialogBody className="space-y-3">
            <div className="rounded-md border p-3 text-sm">
              <div className="flex justify-between gap-4">
                <span className="text-muted-foreground">نام کاربری</span>
                <code dir="ltr">{created.username}</code>
              </div>
              <div className="mt-2 flex justify-between gap-4">
                <span className="text-muted-foreground">رمز عبور</span>
                <code dir="ltr" className="break-all">
                  {created.password}
                </code>
              </div>
            </div>
            <Button variant="outline" onClick={() => void copy()} className="w-full">
              <Copy className="size-4" />
              {copied ? 'کپی شد' : 'کپی نام کاربری و رمز'}
            </Button>
          </DialogBody>
          <DialogFooter>
            <Button onClick={onClose}>کپی کردم، ببند</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    )
  }

  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>نماینده جدید</DialogTitle>
          <DialogDescription>
            یک حساب ورود و یک پرونده‌ی نمایندگی با هم ساخته می‌شوند.
          </DialogDescription>
        </DialogHeader>
        <DialogBody className="space-y-4">
          <Field label="نام کاربری ورود" hint="فقط حروف کوچک انگلیسی، عدد، نقطه و خط تیره">
            <Input
              dir="ltr"
              value={username}
              onChange={(event) => setUsername(event.target.value.toLowerCase())}
              placeholder="north"
            />
          </Field>
          <Field label="نام نمایندگی">
            <Input
              value={nameFa}
              onChange={(event) => setNameFa(event.target.value)}
              placeholder="نمایندگی شمال"
            />
          </Field>
          <Field
            label="درصد تخفیف"
            hint="روی قیمت هر پلن اعمال می‌شود. حداکثر ۹۰ — پلنی که برای نماینده رایگان تمام شود، اشتباه است."
          >
            <Input
              dir="ltr"
              inputMode="numeric"
              value={discount}
              onChange={(event) => setDiscount(event.target.value)}
            />
          </Field>
          <Field label="راه تماس" hint="اختیاری — شماره، آیدی تلگرام، هرچه لازم دارید">
            <Input value={contact} onChange={(event) => setContact(event.target.value)} />
          </Field>
          {error ? <p className="text-sm text-destructive">{error}</p> : null}
        </DialogBody>
        <DialogFooter>
          <Button variant="outline" onClick={onClose}>
            انصراف
          </Button>
          <Button disabled={!valid || busy} onClick={() => void submit()}>
            {busy ? 'در حال ساخت…' : 'بساز'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
